version: "3"
services:
    vjezba-sql:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        restart: unless-stopped
        environment:
            SA_PASSWORD: "HelloWorld123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        ports:
            - 1401:1433
        networks:
            - vjezbanet

    vjezba-api:
        restart: unless-stopped
        build: .
        environment:
            - ConnectionStrings:DefaultConnection=Server=vjezba-sql,1433;Database=eProdaja;User=sa;Password=HelloWorld123;
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - 5192:5192
        networks:
            - vjezbanet
        depends_on:
            - vjezba-sql
        links:
            - vjezba-sql 

networks:
  vjezbanet:
    driver: bridge